### ISSUE TITLE
Feedback TaggedEventKeyedSubscriber

### ISSUE THREAD

**Issue by patriknw** [sean-walsh/akka-saga#4]
**Error handling**

Nothing takes care of failures from the `query.eventsByTag` stream. It will probably just stop and and no more events published to the eventStream.

`RestartSource` can be used for restarting failing streams (with exponential backoff).

**UpdateOffset**

I'm not sure I follow how `UpdateOffset` but it looks like a new `query.eventsByTag` stream is started for each received `UpdateOffset` without stopping the previous ongoing query.

`KillSwitch` can be used to shutdown a stream.

**limit**

`limit(1)`? Looks like the query only retrieves one single element? This will be very inefficient and will not scale, see next...

**one query per saga**

My original concern in https://github.com/sean-walsh/akka-saga/pull/2/files#diff-2094adfa0d262f5fa9c17b5743028056R145 was that it will not scale to have one query per transaction/saga. This is still a problem, since it's starting one `TaggedEventKeyedSubscriber` per transactionId.

Instead, I think the `TaggedEventSubscriptionManager` should start one single `eventsByTag` stream for all events and publish them to the local `eventStream`.

The tagging would not be per transactionId, but one single tag for everything.

The `PersistentSagaActor`s would subscribe to all events via the local `eventStream` and filter the events of interest on the transactionId.

I might be missing something (of importance) for the overall design here, such as how to manage the offsets, but the approach with one query per transaction/saga will not scale.

**Comment by sean-walsh** [comment]
I thought through this a bit. The one problem I'm imagining is that each node generates a unique tag and all events are tagged with that. If and when the node goes down with outstanding events, those events would never be received again. I'm sure I can come up with something but it feels like a smell, requiring a step back.

**Comment by sean-walsh** [comment]
I think the solution to the above is when a saga actor restarts on a different node it will instantiate it's own stream subscription for the duration of the saga *SNAP
